#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["TAN.Core.3.1.WindowsService/TAN.Core.3.1.WindowsService.csproj", "TAN.Core.3.1.WindowsService/"]
RUN dotnet restore "TAN.Core.3.1.WindowsService/TAN.Core.3.1.WindowsService.csproj"
COPY . .
WORKDIR "/src/TAN.Core.3.1.WindowsService"
RUN dotnet build "TAN.Core.3.1.WindowsService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TAN.Core.3.1.WindowsService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TAN.Core.3.1.WindowsService.dll"]